name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - "README.md"
      - ".vscode/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
